sonar.projectKey=ha_refactor_alexa
sonar.sources=homeassistant/components/alexa
sonar.language=py
sonar.host.url=http://localhost:9000
sonar.token=sqp_e4940781bece34d040f656f1f2bc780818a6ab75
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git